name: CI/CD Pipeline - PR Flow with GitHub Package

on:
  # Eventi che triggerano la pipeline
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  # Job di validazione per Pull Request (PR Validation)
  pr-validation:
    name: Validate Pull Request
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build PR Docker Image
        run: |
          cd test-docker
          docker build -t ghcr.io/ffppa/test-runners/test-docker:PR.${{ github.event.pull_request.number }} .
          echo "Docker image built: PR.${{ github.event.pull_request.number }}"

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push PR Docker Image to GitHub Container Registry
        run: |
          docker push ghcr.io/ffppa/test-runners/test-docker:PR.${{ github.event.pull_request.number }}


