
name: Docker GA Workflows

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: write
  issues: write

jobs:
  # Build PR images
  pr-build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Build and promote PR image
        uses: pagopa/eng-github-actions-iac-template/global/docker-ci-image-workflows/build-pr@PAYMCLOUD-480-new-workflow-deploy
        with:
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile_path: './test-docker/Dockerfile'
          docker_context: './test-docker'

  # Build MA images on main
  main-build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Build and promote MA image
        uses: pagopa/eng-github-actions-iac-template/global/docker-ci-image-workflows/build-and-promote-ma@PAYMCLOUD-480-new-workflow-deploy
        with:
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile_path: './test-docker/Dockerfile'
          docker_context: './test-docker'
